### ISSUE TITLE
Inconsistent exportRecords behavior

### ISSUE THREAD

**Issue by Wunsei** [nutterb/redcapAPI#16]
I posted back in October regarding the exportRecords function no longer working, but after a day or two, it suddenly started working again. It worked most of the time, but I would occasionally still get the following error:
```
Error in redcap_error(x, error_handling = error_handling) : 
  400: ERROR: An unknown error occurred. Please check your API parameters.
```
After restarting my computer, this error would usually stop occurring. Sometimes I would have to wait, but it would usually resolve itself within a day or two. However, I just changed to a new PC and the error persists.

Why might this be happening? I change nothing in the code -- sometimes I get the error, other times I'm able to pull all the data with no issues.

**Comment by spgarbet** [comment]
I think the current version may have this fixed at https://github.com/vubiostat/redcapAPI . @Wunsei can you see if this is working now?

**Comment by Wunsei** [comment]
The problem persists, albeit not as frequently as before. Perhaps the database is still too large? It currently holds almost ten thousand records.

**Comment by Wunsei** [comment]
Curiously, if the error occurs, an immediate re-run also fails. However, if I wait 10 minutes before running, it almost always succeeds. Wonder what the explanation for this is.

**Comment by spgarbet** [comment]
I suspect a load issue. https://github.com/vubiostat/redcapAPI/issues/41

**Comment by nutterb** [comment]
Should be resolved by https://github.com/vubiostat/redcapAPI/pull/64

**Comment by Wunsei** [comment]
Is exportRecordsTyped usable right now? If so, it's not working for me.

**Comment by nutterb** [comment]
It should be. Some questions

1. When did you install it? There have been a couple of minor pushes today.
2. What does your call look like.
3. What error/result are you getting? and what were you expecting?

We're very interested in making this work.

**Comment by Wunsei** [comment]
1. I reinstalled around 10 mins before this post.
2. All I did was change `exportRecords` to `exportRecordsTyped` with no other changes. `exportRecords` still appears to be working.
3. I simply get the result `could not find function "exportRecordsTyped"`.

Am I somehow installing this package wrong?

**Comment by nutterb** [comment]
try installing with `devtools::install_github("vubiostat/redcapAPI")`. 

Sorry for the confusion. We haven't pushed this to CRAN yet. We've been cleaning out issues to figure out what comes next. If all goes well, you should be on version 2.7.0 (`packageVersion("redcapAPI")`)

**Comment by spgarbet** [comment]
This is the development version. It is a great time to give it a try. We are really engaged and want this to be a success. Note: The function interface has changed. This is why it has a different name as it is a breaking change.. What parameters are you calling it with?

**Comment by Wunsei** [comment]
This is what my call looks like: `exportRecordsTyped(rcon, labels = FALSE, dag = FALSE)`

I installed RTools42 and devtools and installed the package from Github. The problem persists, thought not as badly as before. Now, when I attempt to pull the data, I sometimes get an empty dataframe with a single column titled `An unknown error occurred. Please check your API parameters.`.

I tried again and the call succeeded. Now I'm getting an additional error: when I use
```
foo[,8:55] <- lapply(foo[,8:55], redcapFactorFlip)
```
I get the error
```
Error in FUN(X[[i]], ...) : This does not appear to be a REDCap factor.
```
This error did not occur in the previous build. Any idea why this might be happening?



As an aside, I'm very thankful for the continued development of this project. The hospital database I manage is critical infrastructure for for clinical, research, and administrative teams. This package is the cornerstone of that infrastructure.

**Comment by nutterb** [comment]
We didn't implement the `redcapFactor` class with the new `exportRecordsTyped` function because, honestly, the `redcapFactor` class doesn't work as well as we would like. 

I appreciate your patience helping us out with this. If you don't mind, I'd like to ask a couple questions about what your desired output is to see if `exportRecordsTyped` can get you what you desire. 

1. Am I correct that you are wanting the coded values from your data base instead of the labelled values. For instance, you want your check boxes to be coded 0/1 instead of "Unchecked"/"Checked"?
2. You do not want the variable labels attached to your data?
3. Are there more than 55 columns, and it is only columns 8 - 55 that need to be coded values?

**Comment by spgarbet** [comment]
Also I think `labels=FALSE` is no longer required. I suspect this is just ignored.

**Comment by spgarbet** [comment]
@nutterb ` An unknown error occurred. Please check your API parameters.` This message is odd. The code formats the API the same way everytime. This might be caught up in that changing API parameter call syntax issue by REDCap version number.

**Comment by Wunsei** [comment]
1. Yes, I want numeric values. It's to make the data easier to graph.
2. Correct, just the data itself. Again, makes it easier to graph.
3. Correct. There are more than 55 columns, and only columns 8-55 need to be coded.

**Comment by nutterb** [comment]
Hmmm...we haven't written an equivalent of redcapFactorFlip yet. I might need a day or two to come up with something I like. 

In the meantime, `exportRecords` is unchanged. Hopefully that will work a little better with some of the new features we've put in around the actual API calls.  I'll let you know when I've got something that can switch between codings.

**Comment by Wunsei** [comment]
Thanks so much, Benjamin. Your work on this project is having a massively positive impact on clinicians, researchers, patients, and administrative staff alike.

**Comment by spgarbet** [comment]
The purpose of exportRecordsTyped is to get the data in exactly the format one wants out with a single call. Would `redcapFactorFlip` be needed downstream if this were the case? Is the problem that one wants some of the values in one format and others in the opposite?

**Comment by nutterb** [comment]
@Wunsei, if you reinstall from Github, you should be able to get the same results with

```
Records <- exportRecordsTyped(rcon)
Records <- recastRecords(Records, 
                         rcon, 
                         fields = 8:55, 
                         cast = list(dropdown = castRaw, 
                                     radio = castRaw, 
                                     checkbox = castRaw))
```

I'm not sure what the field types are in your columns 8:55, but that should cover most of it. It's a different style than what we had before, but I think it's going to have a lot of benefits going forward.
