### ISSUE TITLE
Error in exportRecords.redcapApiConnection(rconn, forms = "co") :    'co are not valid form names

### ISSUE THREAD

**Issue by JRW-UCSF** [nutterb/redcapAPI#87]
I am trying to use this package to access my RedCap data directly through R. The project has over 2700 variables over multiple forms. Since bringing in all of the data all at once would make an unwieldy data frame for my analysis I wanted to export only one form.

I setup my connection to R and can export all of the RedCap data. However, when I try to only export the form I am interested in I get an error message that it is not a valid form name.

```
> df <- exportRecords(rconn, forms = 'co')
Error in exportRecords.redcapApiConnection(rconn, forms = "co") : 
  'co are not valid form names
```

This should be the correct form name as it appears when you look at the event-form mappings for the project

```
> exportMappings(rconn)[1:13,]
    arm_num        unique_event_name                                form
1        1      reclutamiento_arm_1                     registro_diario
2        1 evaluacion_prenata_arm_1          evaluacion_prenatal_medica
3        1  a_visita_prenatal_arm_1               linea_basal_domicilio
4        1  a_visita_prenatal_arm_1 monitoreo_de_contaminacion_del_aire
5        1  a_visita_prenatal_arm_1                        hap_visita_1
6        1  a_visita_prenatal_arm_1           prenatal_visit_domicilio1
7        1  a_visita_prenatal_arm_1                        hap_visita_2
8        1  a_visita_prenatal_arm_1                                 pah
9        1  a_visita_prenatal_arm_1                      food_diversity
10       1  a_visita_prenatal_arm_1                       food_security
11       1  a_visita_prenatal_arm_1                        hap_visita_3
12       1  a_visita_prenatal_arm_1                           pm_filtro
13       1  a_visita_prenatal_arm_1                                  co  
```

However, looking at the code on GitHub, I saw that the exportRecords command checks the metadata to validate any input form names but when I export the metadata using this package it comes out empty

```
> exportMetaData(rconn)
[1] NA.
<0 rows> (or 0-length row.names)
```

**Comment by nutterb** [comment]
are you using the CRAN version (1.3), or the GitHub version (1.3.7)?

**Comment by JRW-UCSF** [comment]
I was using the CRAN version. I also just installed and tried the GitHub version (1.3.7) which gave the same error message.

**Comment by nutterb** [comment]
I am unable to reproduce this error.  May I request a copy of your data dictionary .csv (just the data dictionary, please don't send data)?  Please be sure to e-mail it directly to benjamin.nutter@gmail.com.  Sending it through the Issues doesn't actually attach the file.

Thanks

**Comment by nutterb** [comment]
Here's another thing to try.  Define your `rcon` object and then run this code:

```
x <- httr::POST(url = rcon$url, 
           body = list(token = rcon$token,
                       content = "metadata",
                       format = "csv",
                       returnFormat = "csv"), 
           config = httr::config())

dput(x)
```

If you share with us the output, it will tell us a lot about where the issue is occurring.  This is the code to call the API, so whatever we get here tells us if the problem is occurring at the API or within `redcapAPI`.

**Comment by nutterb** [comment]
Thanks for sending me your files.  When I tried to upload your metadata into REDCap, I was presented with three errors, shown below.  When I corrected the formatting on those fields, I was able to upload the meta data and download the result.  

Based on what I'm seeing, it appears you have three fields where the options for the radio buttons are not correctly specified.  It's showing up with a fourth, unindexed option in these fields. That hopefully is the root of the problem.  If that isn't it, we may need to play with the encoding in `httr::config()`.

could you try looking at the variables in the message below and correcting the definitions of those radio button options?  You may not be able to see the problem...it might be a relic of a copy/paste from a document, for example.  If there doesn't appear to be anything in error, I would delete the text in the "choices" field and manually retype it.  I'm attaching an image for reference.

Let me know if that helps at all

![redcap metadata error](https://user-images.githubusercontent.com/1848445/29980326-5c17f5b6-8f17-11e7-99c1-b4b2d364203d.PNG)
![redcap correction](https://user-images.githubusercontent.com/1848445/29980330-610e2496-8f17-11e7-8698-73548b6ac199.PNG)

**Comment by JRW-UCSF** [comment]
Thanks. I made those changes; they were a remnant from a bad cut/paste when I made some changes. After the changes it still won’t export the data for only the one survey, only the entire project:


> test_2 <- exportRecords(rconn)

> test_2 <- exportRecords(rconn, forms = 'co')
Error in exportRecords.redcapApiConnection(rconn, forms = "co") :
  'co are not valid form names

This is what I get when I try to export the metadata through the package:


> exportMetaData(rconn)

[1] NA.

<0 rows> (or 0-length row.names)


I’m sorry for all of the trouble. This project is nearly over but we are starting a much larger, longer project so I want to make sure I can get the package to work so I can update the data through R rather than having to manually download the data. Thanks.

~John

**Comment by nutterb** [comment]
This is stumping me.  I'm becoming increasingly confident that this is an issue in the meta data itself. But let's try a couple more things.  I'll start with the least drastic to the most drastic.

#### add an encoding argument to your `rconn`.  

Try defining

```
rconn <- redcapApiConnection(url = your_url,
                             token = your_token,
                             config = list(encoding = "identity"))

exportMetaData(rconn)
```

#### Try upgrading the `redcapAPI` 2.0.  
This is still in development, but should be stable enough to work (but it has not import method yet).

Run 

```
devtools::install_github("nutterb/redcapAPI", ref = "Version2")

rconn <- redcapApiConnection(url = your_url,
                             token = your_token,
                             config = list(encoding = "identity"))

exportMetaData(rconn)
```

#### Try making a new project

In this attempt, we'll create a new REDCap project and import the data dictionary to the new project.  If we can import the data dictionary and then export it through the API, that's a good indication that there's something strange in the current project.    Here are the steps to run the test.

1. Create a new project in REDCap
2. Download the data dictionary from the current project
3. Upload the data dictionary to the new project
4. Request an API token for the new project
5. Attempt to export the data dictionary via `exportMetaData`

If that works, you'll want to carefully proceed with the help of your REDCap Administrators.  I can lay out the general steps, but I won't do that unless the test works.

**Comment by nutterb** [comment]
I don't know if you ever were able to resolve this.  I just put in a change to strip non-ASCII characters out of the records and meta data.  Would you be willing to try again after running

`devtools::install_github("nutterb/redcapAPI", ref = "Version2")`

**Comment by JRW-UCSF** [comment]
I tried running it but this was the error I received:

`devtools::install_github('nutterb/redcapAPI', ref = "Version2")`
Downloading GitHub repo nutterb/redcapAPI@Version2
from URL https://api.github.com/repos/nutterb/redcapAPI/zipball/Version2
Installing redcapAPI
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet  \
  CMD INSTALL  \
  "C:/Users/SF691362/AppData/Local/Temp/RtmpCwZOn0/devtools3b4c43a377b9/nutterb-redcapAPI-bb945b3"  \
  --library="C:/Program Files/R/R-3.4.2/library" --install-tests 

* installing *source* package 'redcapAPI' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error : package 'redcapAPI' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.4.2/library/redcapAPI'
* restoring previous 'C:/Program Files/R/R-3.4.2/library/redcapAPI'
Warning in file.copy(lp, dirname(pkgdir), recursive = TRUE, copy.date = TRUE) :
  problem copying C:\Program Files\R\R-3.4.2\library\00LOCK-nutterb-redcapAPI-bb945b3\redcapAPI\libs\x64\redcapAPI.dll to C:\Program Files\R\R-3.4.2\library\redcapAPI\libs\x64\redcapAPI.dll: Permission denied
Installation failed: Command failed (1)

**Comment by nutterb** [comment]
Oi. R is complaining about deleting the old package version. try adding the `force = TRUE` argument. if that doesn't work, navIgate to your library (`.libPaths ()`) and then try it.

**Comment by nutterb** [comment]
@JRW-UCSF Have you tried exporting a form recently?  A new version went to CRAN in January that is pretty aggressive with respect to non-ASCII characters in the meta data (perhaps too aggressive).  I'm hoping that might be somewhat helpful though.
